package com.muxistudio.jobs.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "HISTORY".
 */
@Entity
public class History {

    @Id
    private Long id;
    private String query;
    private String mail;

    @Generated
    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    @Generated
    public History(Long id, String query, String mail) {
        this.id = id;
        this.query = query;
        this.mail = mail;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

}
