package com.muxistudio.jobs.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "JOBS".
 */
@Entity
public class Jobs {

    @Id
    private Integer id;
    private String logoUrl;
    private String title;
    private String place;
    private String time;
    private Integer clicks;

    @Generated
    public Jobs() {
    }

    public Jobs(Integer id) {
        this.id = id;
    }

    @Generated
    public Jobs(Integer id, String logoUrl, String title, String place, String time,
            Integer clicks) {
        this.id = id;
        this.logoUrl = logoUrl;
        this.title = title;
        this.place = place;
        this.time = time;
        this.clicks = clicks;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLogoUrl() {
        return logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getClicks() {
        return clicks;
    }

    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

}
